name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install
        run: npm ci

      - name: npm build, test, and copy files to dist dir
        run: |
          npm run build:css
          npm test
          npm run copy:dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            dist
