name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, test, and copy files to dist dir
        run: |
          npm install
          npm run build:css
          npm test
          npm run copy:dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            dist
